base_url = "https://minimagate.github.io/personal-website"
title = "Michelangelo Gubinelli"
description = "Designer, developer, founder at Logven, and mathematics student."
default_language = "en"
author = "Michelangelo Gubinelli"
compile_sass = false
minify_html = true

[markdown]
smart_punctuation = true

[extra]
github = "https://github.com/minimagate"
logven = "https://logven.com"
